### PR TITLE
Fix some localizations

### PR DESCRIPTION
**Pull request by mlocati**
This is a work in progress pull request, fixing some strings that are not localized.

Linked to https://github.com/concrete5/concrete5/pull/10122

### CODE REVIEW

**Comment by mlocati** [comment]
This PS is ready for review

I think the test fails because in the `package-lock.json` we tell `npm` to use the ssh protocol. Using the plain https protocol should work.

That is, instead of
```
git+ssh://git@github.com/concrete5/bootstrap-tourist.git
```
we should have
```
https://github.com/concrete5/bootstrap-tourist.git
```

**Comment by mlocati** [comment]
> I think the test fails because in the `package-lock.json` we tell `npm` to use the ssh protocol.

See https://github.com/concrete5/bedrock/pull/189

**Comment by aembler** [comment]
I've merged the PR in – you want to update and try again?

**Comment by mlocati** [comment]
> I've merged the PR in – you want to update and try again?

The link job now runs successfully (and I fixed the linting issues).

`npx build-storybook` still fails: I think it's because we are using rather old package versions.
For example, we are using webpack ^4.33, but many dependencies require a more recent version of it (for example, postcss-loader 5+ requires webpack 5+)

**Comment by aembler** [comment]
Thanks you @mlocati !

I've merged this into bedrock and published it as 1.1.0. I've update the develop branch of concrete to include the 1.1.0 release.

I haven't had a chance to go through everything but what I've gone through has worked well.

**Comment by mlocati** [comment]
That was just a first and (not so) quick pass.
I'll translate the new strings with https://translate.concretecms.org and check if there's still something to be done.

**Pull request merged**
