### PR TITLE
Feature/file manager update

### PR DESCRIPTION
**Pull request by bitterdev**

### CODE REVIEW

**Comment by bitterdev** [comment]
Bootstrap Select component was added in this commit. MIT license (https://github.com/snapappointments/bootstrap-select/blob/v1.13.0-dev/LICENSE)

**Comment by aembler** [comment]
Couple questions about this..

1. Can you explain why you've added back functionality that was explicitly removed prior to this? That functionality doesn't really have a place in the in-page file manager, and more of the in-page file manager functionality in here is going to be removed soon as well. The in-page file manager is going to primarily be a Vue component limited to very specific functionality that doesn't really have much to do with the old javascript approach.

2. Can you explain why you merged a new component (bootstrap select) as opposed to using selective, which we've used elsewhere for this type of functionality, and which we've updated to a Bootstrap 4 theme so that it looks nice? If there is functionality you need from this component I'd be happy to discuss it but I think we should stick with selectize unless there's a real specific need.

**Comment by bitterdev** [comment]
Hello @aembler,

1. I don't have added anything new on functionality. Can you please tell me which functionality you are talking about in detail? If you are talking about the views: In general i performed a big clean up within this task because the code was hard to work with and there was a lot of deprecated stuff like old loader calls for example. In this clean up i have edited all views that are related to the file manager. In-page editor views also. From the [task description](https://github.com/concrete5/concrete5/issues/8581) it was not clearly specified that in-page-editing should not be supported. This information if firstly received later when we had a small chat on slack. But at this point i already had refactored the views.

2. I was looking for a bootstrap 4 compatible solution that supports icons and custom css classes. As far as i can see Selectize.js doesn't support this. I have read through [the docs](https://github.com/selectize/selectize.js/blob/master/docs/api.md) + [check the demo page](http://selectize.github.io/selectize.js/) and it seems there is not such an option. Maybe with some hacks it will work anyway but i was looking for a clean solution.

**Comment by aembler** [comment]
Thanks – in the future please let me know before adding a new component, or ask. I think selective would work in the case, however I've had a chance to look over bootstrap select and it seems to be better supported going forward. So right now I'm going to approve Bootstrap select for use here, and we can look at migrating to it away from selectize for some of our core UI components that we use selective for.

**Comment by aembler** [comment]
Looks really good. I've updated some of the legacy-dialog.js to make your dialogs look better. Before, when you used the jQuery UI dialog programmatically the dialogs looked a lot different than standard concrete5 dialogs. No background overlay, no animation, etc... This is fixed.

**Pull request merged**
