### PR TITLE
Feature/panel seo ui updates

### PR DESCRIPTION
**Pull request by mnakalay**
This requires a companion pull request in the core: https://github.com/concrete5/concrete5/pull/8531

The Concrete5 issue it addresses is https://github.com/concrete5/concrete5/issues/8479

All the details are to be found there.

### CODE REVIEW

**Comment by deek87** [comment]
Your build is probably not building due to this commit https://github.com/concrete5/bedrock/pull/19/commits/38ec21cea8d05c1999e8c8bb1ab97efece16cf13
where you removed package-lock.json
Can you revert removing package-lock.json

**Comment by mnakalay** [comment]
thank you @deek87 sorry I didn't see your comment right away...

**Comment by mnakalay** [comment]
@deek87 a little help, please. I am not sure how to resolve conflicts within the package-lock file. For each conflict, it gives me the choice between 2 totally different resources. Should I keep both every time?
Example:

```
<<<<<<< feature/panel-seo-ui-updates
    "assert-plus": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz",
      "integrity": "sha1-8S4PPF13sLHN2RRpQuTpbB5N1SU=",
      "optional": true
=======
    "@babel/helper-hoist-variables": {
      "version": "7.8.3",
      "resolved": "https://registry.npmjs.org/@babel/helper-hoist-variables/-/helper-hoist-variables-7.8.3.tgz",
      "integrity": "sha512-ky1JLOjcDUtSc+xkt0xhYff7Z6ILTAHKmZLHPxAhOP0Nd77O+3nCsd6uSVYur6nJnCI029CrNbYlc0LoPfAPQg==",
      "dev": true,
      "requires": {
        "@babel/types": "^7.8.3"
      }
>>>>>>> master
```

**Comment by mnakalay** [comment]
All good now

**Pull request merged**
