### PR TITLE
 Migrate top level tools scripts into the routing/controller/view system

### PR DESCRIPTION
**Pull request by mlocati**
Companion of https://github.com/concrete5/concrete5/pull/9088

### CODE REVIEW

**Comment by aembler** [comment]
Is this PR still in progress or can we move it over to mergeable?

**Comment by mlocati** [comment]
I'm waiting for https://github.com/concrete5/concrete5/pull/9088#issuecomment-701921213

**Comment by aembler** [comment]
Got it. I missed that. Yes, I believe you can remove all those things.

**Comment by aembler** [comment]
I think you need to publish this so I can merge it in  (it's still a draft)

**Comment by mlocati** [comment]
> I think you need to publish this so I can merge it in (it's still a draft)

Whoops... done

**Pull request merged**
