### PR TITLE
Feature/add block panel

### PR DESCRIPTION
**Pull request by mnakalay**
This requires a companion pull request from the core https://github.com/concrete5/concrete5/pull/8578

It addresses core issue #8475

### CODE REVIEW

**Comment by mnakalay** [comment]
OK i'm on it

**Comment by mnakalay** [comment]
Actually one comment:
3. that is indeed an expand/collapse using Bootstrap expand/collapse with just the appropriate data attributes. It was working I wonder what changed? I'll have a look

**Comment by mnakalay** [comment]
Hi @aembler 
I took care of 1, 2 and 4.

I also took care of 5 but what I did was keep it an accordion with an extra class and some styling that turns it into a dropdown. That way no need for extensive markup changes and it also leaves the JS attached to it still working.
Using that new class on any BootStrap accordion should make it work like a dropdown so since it's reusable I put it in the _shared.scss file

Could you tell me what error you get for 3? I don't have any error and it works. It is indeed a BootStrap expand/collapse and I only use a bit of jQuery to switch the arrow up and down nothing else.

As for 6 because of the way the dragging works and because we now have list and grid views, I had to make a choice and hide the block's name when the dragging starts. There was just no way to accommodate the different sizes and styling when dragging, without lots of JS modification. I had to do some but kept it to a minimum.

**Comment by aembler** [comment]
Generally looks good, with one big issue (see the end), but first:

1 and 2 look great. Really like the update and the transition. Nice job.

3: This appears to be due to us upgrading to jQuery 3.5. I don't know why we did that, that certainly wasn't something I specifically wanted to do. This may have been introduced in a dependency update. https://github.com/twbs/bootstrap/issues/30553. You can ignore this issue.

4. Looks great.

5. The dragging style actually looks a lot better to me now, maybe something wasn't being loaded in properly.

--
The issue:

Something has gone haywire with transitions and dragging in this update. I expect it might have to do with with the flex display on the icon, or something similar. But now my icons are jumping all over the place when I switch grid views, and the dragging behavior looks crazy. Check out these gifs.

Dancing icons (which we don't want):

dancingicons

Strange dragging behavior:

draghell

Thanks, this looks really close!

**Comment by mnakalay** [comment]
that was $transition-base causing the issue. I replaced it with $btn-transition it fixed both view and dragging issues.

**Comment by aembler** [comment]
Thanks! This looks great.

**Pull request merged**
