### PR TITLE
Feature #5845 . Add Edit In composer menu item

### PR DESCRIPTION
**Pull request by SashaMcr**
Adding "Edit in composer" in Sitemap

Add feature #5845 . Required for https://github.com/concretecms/concretecms/pull/11889

image

### CODE REVIEW

**Comment by aembler** [comment]
If we're going to implement this we should do so in a semantically correct way. We should modify the core to be explicit that it's editing a page in composer, not use the weird "ccmCheckoutFirst" query string variable which really doesn't mean anything (it exists because it was meant to indicate that this was the first time the page was checked out for editing so it should open in composer mode.) but really we should make this semantically correct and rename

**Comment by hissy** [comment]
@aembler @SashaMcr 

So we should add `ccmEditMode` or something similar query near this code?

https://github.com/concretecms/concretecms/blob/984b7eb0cf14c8df22b5617ea431f5680ab97d92/concrete/elements/page_controls_header.php#L48-L53

**Comment by aembler** [comment]
Yeah, I think that would probably be good. I'm not in love with the `ccm*` query string variables that we're using here but they've been in use here for awhile so I think it's probably fine.

**Comment by aembler** [comment]
I think this needs to be reworked - this doesn't check to see whether the page _can_ be edited in Composer, for example.

**Pull request closed without merging**
